name: cinemateca  # Nome do seu projeto (sem espaços ou caracteres especiais)
description: Aplicativo de gerenciamento de filmes em Flutter.  # Descrição opcional
version: 1.0.0+1  # Versão (formato: versão+build)

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.2
  path: ^1.8.3
  flutter_rating_bar: ^4.0.1
  smooth_star_rating_null_safety: ^1.0.4+2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true